// SC BUG BOT XHIRO GENERASI KE TIGA 
// BASE : RAFATHARCODE
// RECODE FULL : NOXXHIRO / XHIRO
// USAHAKAN GUNAKAN BOT SEBAIK MUNGKIN
// BUY NO ENC? SUNG KELEGRAM OWNER
// @NOXXHIRO

//GUNAKAN BOT SEWAJARNYA BIAR GAK KENA BANNED
//XHIRO BOT GENERASI 3

//INFO BOT XHIRO GEN 3
//BASE : RAFATHAR CODE
//RECODE : XHIRO

//===============================//
// SC BUG BOT XHIRO GENERASI KE TIGA 
// BASE : RAFATHARCODE
// RECODE FULL : NOXXHIRO / XHIRO
// USAHAKAN GUNAKAN BOT SEBAIK MUNGKIN
// BUY NO ENC? SUNG KELEGRAM OWNER
// @NOXXHIRO

//GUNAKAN BOT SEWAJARNYA BIAR GAK KENA BANNED
//XHIRO BOT GENERASI 3

//INFO BOT XHIRO GEN 3
//BASE : RAFATHAR CODE
//RECODE : XHIRO
//CREDITS : NOXXHIRO
//YOUTUBE : https://www.youtube.com/@akhiroc-nine
//===============================//